# mkl 2021 until dependencies get rebuild against 2022
mkl:
  - 2021.*
# openblas 0.3.21 has better osx-arm64 support than openblas 0.3.20
openblas:
  - 0.3.21
c_compiler_version:    # [osx and arm64]
  - 12                 # [osx and arm64]
cxx_compiler_version:  # [osx and arm64]
  - 12                 # [osx and arm64]
