c_compiler_version:        # [osx]
  - 17                     # [osx]
cxx_compiler_version:      # [osx]
  - 17                     # [osx]

fortran_compiler_version:  # [osx]
  - 11.3.0                 # [osx]