{% set version = "1.5.4" %}

package:
  name: scipy
  version: {{ version }}

source:
  url: https://github.com/scipy/scipy/archive/v{{ version }}.tar.gz
  sha256: 0d47f253609197c77b1b14ac813e1726f5dbaac7f4d9827d7e667a6a596793ae
  patches:
    - patches/0001-fortran-test-endianness.patch
    # removing assert based on expected dtype for little-endian systems.
    - patches/0002-arff-nodata-test-remove-endian-check.patch                 # [s390x]
    # Very similar patch was a part of the initial ppc64le builds. Applying for s390x.
    - patches/0004-relax-precision-in-sparse-linalg-isolve-lsmr-test.patch    # [s390x]
    # Very similar patch was a part of the initial ppc64le builds. Applying for s390x.
    - patches/0005-backport-gaussian-kde-fix.patch                            # [s390x]

build:
  number: 2
  skip: True  # [blas_impl == 'openblas' and win]
  skip: True  # [py<34]

requirements:
  build:
    # on windows, Parallel studio activates the appropriate c/cxx compiler
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('fortran') }}
  host:
    - python
    - setuptools
    - cython
    - pybind11
    - numpy-devel  {{ numpy }}
    - pip
    - mkl-devel  {{ mkl }}  # [blas_impl == 'mkl']
    # pin intel-openmp to the same version as mkl, without this build may fail with
    # Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.
    # It may be needed to make this pinning explicit in the mkl package
    - intel-openmp {{ mkl }}  # [blas_impl == 'mkl']
    - openblas-devel {{ openblas }}  # [blas_impl == 'openblas']
    - msinttypes   # [win and vc<14]
  run:
    - python

test:
  requires:
    - pytest
    - pytest-xdist
    - mpmath
    # see commend above
    - intel-openmp {{ mkl }}  # [blas_impl == 'mkl']

about:
  home: http://www.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Scientific Library for Python
  description: |
    SciPy is a Python-based ecosystem of open-source software for mathematics,
    science, and engineering.
  doc_url: http://www.scipy.org/docs.html
  dev_url: https://github.com/scipy/scipy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - rgommers
    - ocefpaf
