{% set version = "0.18.1" %}

{% set variant = "openblas" %}


package:
  name: scipy
  version: {{ version }}

source:
  fn: scipy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/scipy/scipy-{{ version }}.tar.gz
  sha256: 8ab6e9c808bf2fb3e8576cd8cf07226d9cdc18b012c06d9708429a821ac6634e

build:
  number: 201
  # We lack openblas on Windows, and therefore can't build scipy there either currently.
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - gcc          # [osx]
    - python
    - setuptools
    - cython
    - blas 1.1 {{ variant }}
    - libgfortran  # [linux]
    - openblas 0.2.19|0.2.19.*
    - numpy x.x
  run:
    - python
    - blas 1.1 {{ variant }}
    - libgfortran
    - openblas 0.2.19|0.2.19.*
    - numpy x.x

test:
  requires:
    - nose
    - mpmath

about:
  home: http://www.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Scientific Library for Python
  description: |
    SciPy is a Python-based ecosystem of open-source software for mathematics,
    science, and engineering.
  doc_url: http://www.scipy.org/docs.html
  dev_url: https://github.com/scipy/scipy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - rgommers
    - ocefpaf
